version: '3'

services:
  backend:
    image: yutfut/back:${VERSION}
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/html
      - ./certs:/etc/ssl
    depends_on:
      - backend