version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "yutfut"
      POSTGRES_USER: "yutfut"
      POSTGRES_PASSWORD: "yutfut"
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data/
      - ./init_db/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    links:
      - "db:db"
    ports:
      - "8090:8080"
    depends_on:
      - db


  backend:
    image: yutfut/back:${VERSION}
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/html
      - ./certs:/etc/ssl
    depends_on:
      - backend