version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "yutfut"
      POSTGRES_USER: "yutfut"
      POSTGRES_PASSWORD: "yutfut"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
      - ./init_db/:/docker-entrypoint-initdb.d/
      - .:/var/lib/postgresql/data/

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4:5.7
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
#      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped
#    networks:
#      - postgres

  adminer:
    image: adminer
    restart: always
    links:
      - "db:db"
    ports:
      - "8090:8080"
    depends_on:
      - db

  ml:
    image: yutfut/ml:${VERSION}
    restart: always
    ports:
      - '9000:9000'
    depends_on:
      - db
    env_file:
      - .env.ml

  backend:
    image: yutfut/back:${VERSION}
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - ml
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/html
      - ./certs:/etc/ssl
    depends_on:
      - backend

#  networks:
#    postgres:
#      driver: bridge