version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "yutfut"
      POSTGRES_USER: "yutfut"
      POSTGRES_PASSWORD: "yutfut"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
      - ./init_db/:/docker-entrypoint-initdb.d/
      - .:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    links:
      - "db:db"
    ports:
      - "8090:8080"
    depends_on:
      - db

  cg:
    image: yutfut/cg:${CG_VERSION}
    restart: always
    ports:
      - '9001:9001'
    volumes:
      - ./token.json:/app/config
    depends_on:
      - adminer

  ml:
    image: yutfut/ml:${ML_VERSION}
    shm_size: '1gb'
    restart: always
    ports:
      - '9000:9000'
    depends_on:
      - cg

  backend:
    image: yutfut/back:${BACK_VERSION}
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - ml

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/html
      - ./certs:/etc/ssl
    depends_on:
      - backend