name: ci

on: [push]

jobs:
  send_message_1:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 1/2 ${{ github.repository }} start!

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd infrastructure
            sudo docker-compose stop
            sudo docker-compose down
            sudo docker rm -f $(sudo docker ps -aq)
            git pull origin
            sudo docker-compose up -d
#            --env-file ./.env  --env-file ./.env.ml

  send_message_2:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            2/2 ${{ github.repository }} successes!

            -*//*- https://study-ai.ru -*//*-

#  fillingDB:
#    name: Filling DB
#    runs-on: ubuntu-latest
#    needs: deploy
#    steps:
#      - name: executing remote ssh commands to deploy
#        uses: appleboy/ssh-action@master
#        with:
#          envs: GITHUB_SHA
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          script: |
#            cd infrastructure/
#            python3 main.py
#
#  send_message_3:
#    runs-on: ubuntu-latest
#    needs: fillingDB
#    steps:
#      - name: send message
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            3/3 ${{ github.repository }} successes!
#
#            -*//*- https://study-ai.ru -*//*-
