name: ci

on: [push]

jobs:
  send_message_1:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 1/2 ${{ github.repository }} start!

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd infrastructure
#            cd frontend && sudo docker-compose stop
#            cd ../backend && sudo docker-compose stop
#            cd ..
#            sudo docker rm -f $(sudo docker ps -aq)
            git pull origin
#            cd frontend && sudo docker-compose up -d
#            cd ../backend && sudo docker-compose up -d

  send_message_2:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            2/2 ${{ github.repository }} successes!

            -*//*- https://study-ai.ru -*//*-